# Use a base image with Java
FROM openjdk:11-jre-slim

# Set the working directory in the container
WORKDIR /app

# Copy the jar file from the host to the container
COPY target/book-network-api.jar /app/book-network-api.jar

# Expose the port the application runs on
EXPOSE 8088

# Set the entry point to run the jar file
ENTRYPOINT ["java", "-jar", "/app/book-network-api.jar"]
